"""add invite_date to servers table

Revision ID: 0d1dbac6317d
Revises: 36c5aa996d17
Create Date: 2026-07-16 18:57:04.278070

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0d1dbac6317d'
down_revision: Union[str, None] = '36c5aa996d17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
     with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invite_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.drop_column('invite_date')

    # ### end Alembic commands ###
