"""adding reverification to lobbydata

Revision ID: 735998a5e7d1
Revises: ed1c87d614f7
Create Date: 2025-11-01 20:14:32.932541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '735998a5e7d1'
down_revision: Union[str, None] = 'ed1c87d614f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###


    with op.batch_alter_table('lobby_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reverify', sa.Boolean(), nullable=False, server_default=sa.text('false')))



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('lobby_data', schema=None) as batch_op:
        batch_op.drop_column('reverify')


    # ### end Alembic commands ###
