"""Add fields to servers table

Revision ID: ed1c87d614f7
Revises: 1367b4f0e76b
Create Date: 2025-09-20 00:49:20.020280

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ed1c87d614f7'
down_revision: Union[str, None] = '1367b4f0e76b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None :
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column('servers', sa.Column('owner_id', sa.BigInteger(), nullable=True, default=None))
	op.drop_column('servers', 'premium')
	op.add_column('servers', sa.Column('premium', sa.DateTime(timezone=True), nullable=True, default=None))
	op.create_foreign_key(None, 'servers', 'users', ['owner_id'], ['uid'])
	# ### end Alembic commands ###


def downgrade() -> None :
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_constraint(None, 'servers', type_='foreignkey')
	op.drop_column('servers', 'premium')
	op.add_column('servers', sa.Column('premium', sa.Boolean(), nullable=False))
	op.drop_column('servers', 'owner_id')
